// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkuwnqgdpnlfjpfvbjjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdXducWdkcG5sZmpwZnZiampiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDc2MDQsImV4cCI6MjA2NzIyMzYwNH0.Vfp5vLLtdG-rj4ciVrTGs0ltApIe_hQmGzH2eprDbzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});